drop table SSH_EMPLOYEE;
drop table SSH_DEPARTMENT;

CREATE TABLE SSH_DEPARTMENT(
	ID NUMBER(10) PRIMARY KEY,
	DEPARTMENT_NAME VARCHAR2(20) NOT NULL
);
CREATE TABLE SSH_EMPLOYEE(
	ID NUMBER(10) PRIMARY KEY,
	LAST_NAME VARCHAR2(20) NOT NULL,
	EMAIL VARCHAR2(20),
	BIRTH DATE,
	CREATE_TIME DATE NOT NULL,
	DEPT_ID NUMBER(10) REFERENCES SSH_DEPARTMENT(ID)
);
