/*所有类一张表*/
CREATE TABLE T_HIERARCHY(
	ID NUMBER(10) PRIMARY KEY,
	OWNER VARCHAR2(15),
	CODE VARCHAR2(15),
	CREATEED DATE,
	BANKNAME VARCHAR2(20),
	BANKSWIFT VARCHAR2(20),
	CREDIT_CARD_TYPE VARCHAR2(20),
	EXPIRED_MONTH VARCHAR2(20),
	EXPIRED_YEAR VARCHAR2(20),
	ACCOUNT_TYPE VARCHAR2(10)
);

CREATE SEQUENCE T_BILLING_SEQ
START WITH 1
INCREMENT BY 1;

/*每个类一张表*/
CREATE TABLE T_JOIN_BILLINGDETAILS(
	ID NUMBER(10) PRIMARY KEY,
	OWNER VARCHAR2(15),
	CODE VARCHAR2(15),
	CREATED DATE
);

CREATE TABLE T_JOIN_BANKACCOUNT(
	BILLING_ID NUMBER(10) PRIMARY KEY,
	BANKNAME VARCHAR2(20),
	BANKSWIFT VARCHAR2(20),
	FOREIGN KEY(BILLING_ID) REFERENCES T_JOIN_BILLINGDETAILS(ID)
);

CREATE TABLE T_JOIN_CREDITCARD(
	BILLING_ID NUMBER(10) PRIMARY KEY,
	CREDIT_CARD_TYPE VARCHAR2(20),
	EXPIRED_MONTH VARCHAR2(20),
	EXPIRED_YEAR VARCHAR2(20),
	FOREIGN KEY(BILLING_ID) REFERENCES T_JOIN_BILLINGDETAILS(ID)
);

CREATE SEQUENCE T_JOIN_BILLING_SEQ
START WITH 1
INCREMENT BY 1;

/*每个具体子类映射一张表*/
CREATE TABLE T_CONCRETE_BANKACCOUNT(
	ID NUMBER(10) PRIMARY KEY,
	OWNER VARCHAR2(15),
	CODE VARCHAR2(15),
	CREATED DATE,
	BANKNAME VARCHAR2(20),
	BANKSWIFT VARCHAR2(20)
);

CREATE TABLE T_CONCRETE_CREDITCARD(
	ID NUMBER(10) PRIMARY KEY,
	OWNER VARCHAR2(15),
	CODE VARCHAR2(15),
	CREATED DATE,
	CREDIT_CARD_TYPE VARCHAR2(20),
	EXPIRED_MONTH VARCHAR2(20),
	EXPIRED_YEAR VARCHAR2(20)
);

CREATE SEQUENCE T_CONCRETE_BILLING_SEQ
START WITH 1
INCREMENT BY 1;

































