CREATE TABLE T_ENGINEER(
	ID NUMBER(10) PRIMARY KEY,
	NAME VARCHAR2(20) NOT NULL,
	GENDER VARCHAR2(10),
	AGE NUMBER(3) CHECK(AGE BETWEEN 1 AND 100),
	COMPANY VARCHAR2(30)
);

CREATE TABLE T_TECHNOLOGY(
	ID NUMBER(10) PRIMARY KEY,
	NAME VARCHAR2(20) NOT NULL,
	CATEGORY VARCHAR2(20) NOT NULL
);

CREATE TABLE T_ENGINEER_TECHNOLOGY(
	ENGINEER_ID NUMBER(10),
	TECHNOLOGY_ID NUMBER(10),
	PRIMARY KEY(ENGINEER_ID,TECHNOLOGY_ID),
	FOREIGN KEY(ENGINEER_ID) REFERENCES T_ENGINEER(ID),
	FOREIGN KEY(TECHNOLOGY_ID) REFERENCES T_TECHNOLOGY(ID)
);

CREATE SEQUENCE T_ENGINEER_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE T_TECHNOLOGY_SEQ
START WITH 1
INCREMENT BY 1;

