CREATE TABLE BOOK
(
	ISBN VARCHAR2(50) PRIMARY KEY,
	NAME VARCHAR2(30) NOT NULL,
	AUTHOR VARCHAR2(20) NOT NULL,
	PRICE NUMBER(10,2)
);
CREATE TABLE BOOK2
(
	ISBN VARCHAR2(50),
	NAME VARCHAR2(30) NOT NULL,
	AUTHOR VARCHAR2(20) NOT NULL,
	PRICE NUMBER(10,2),
	PRIMARY KEY(ISBN,NAME)
);