CREATE TABLE ACCOUNT
(
	ID NUMBER(10) PRIMARY KEY,
	CODE NUMBER(20) NOT NULL UNIQUE,
	NAME VARCHAR2(20),
	BALANCE NUMBER(10,2)
);

INSERT INTO ACCOUNT VALUES(1,820820,'XIAOBA',1000);

/*version*/
CREATE TABLE ACCOUNT_VERSION
(
	ID NUMBER(10) PRIMARY KEY,
	VERSION NUMBER(10),
	CODE NUMBER(20) NOT NULL UNIQUE,
	NAME VARCHAR2(20),
	BALANCE NUMBER(10,2)
);
INSERT INTO ACCOUNT_VERSION VALUES(1,1,820820,'XIAOBA',1000);

/*timestamp*/
CREATE TABLE ACCOUNT_TIMESTAMP
(
	ID NUMBER(10) PRIMARY KEY,
	TIME_STAMP TIMESTAMP,
	CODE NUMBER(20) NOT NULL UNIQUE,
	NAME VARCHAR2(20),
	BALANCE NUMBER(10,2)
);
INSERT INTO ACCOUNT_TIMESTAMP VALUES(1,SYSTIMESTAMP,820820,'XIAOBA',1000);